sepBundle\Entity\Diesel:
    type: entity
    table: diesel
    id:
        dId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: d_id
            generator:
                strategy: IDENTITY
    fields:
        openingBalance:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: opening_balance
        clossingBalance:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
            column: clossing_balance
        stockPurchased:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: stock_purchased
        stockUsed:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: stock_used
        transportation:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            default: '0'
        netCost:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: net_cost
        date:
            type: date
            nullable: false
            comment: ''
        month:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
        year:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
