sepBundle\Entity\OrdinaryPortlandCementCement:
    type: entity
    table: ordinary_portland_cement_cement
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        openingBalance:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: opening_balance
        clossingBalance:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: clossing_balance
        stockPurchased:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: stock_purchased
        stockUsed:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: stock_used
        netCost:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: net_cost
        date:
            type: date
            nullable: false
            comment: ''
        month:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
        year:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
